### ISSUE TITLE
can't compile bef_executor in debug mode for GPU

### ISSUE THREAD

**Issue by bas-aarts** [tensorflow/runtime#23]
when doing:

bazel build --config=cuda -c dbg //tools:bef_executor
using  clang-10 as the underlying compiler, it errors out with:

ERROR: /home/baarts/tensorflow/runtime/tools/BUILD:106:1: Linking of rule '//tools:bef_executor' failed (Exit 1)
third_party/concurrent_work_queue/lib/task_queue.h:0: error: undefined reference to 'tfrt::internal::TaskQueue::kCapacity'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //tools:bef_executor failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 307.380s, Critical Path: 141.03s
INFO: 870 processes: 870 local.
FAILED: Build did NOT complete successfully
root@a23601beb844:/home/baarts/tensorflow/runtime#

kCapacity is a static data member that doesn't have an out of class definition. This is required for C++ <= 14.
Since this is a headerfile only class definition, there's no obvious location to put the defintion.
Using c++17 instead of c++14 (in .bazelrc) makes the compilation succeed.

**Comment by chuanhaozhuge** [comment]
Thank you for notifying the issue! The bug is fixed with https://github.com/tensorflow/runtime/commit/aa1f5402f7e0768f5f6a97707effcf3bf187be04

We also improved our continuous testing to include building TFRT with all three (fastbuild, dbg, opt) modes.

Currently there are still some issues on building with GCC in debug mode, which we are working on a fix.
